# version: '3.8'  # Removed obsolete version attribute (Docker Compose v2)

services:
  traefik:
    image: traefik:v3.5.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik/letsencrypt:/letsencrypt
      - ./volumes/traefik/logs:/var/log/traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--ping=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"

      # FIXED: Enable access logs for CrowdSec
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--accesslog.format=json"

      # Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"

      # HTTP/3 (QUIC) - Native in v3, no longer experimental
      - "--entrypoints.websecure.http3=true"
      - "--entrypoints.websecure.http3.advertisedport=443"

      # CrowdSec Plugin
      - "--experimental.plugins.crowdsec-bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.crowdsec-bouncer.version=v1.4.5"
    networks:
      - web

  crowdsec:
    image: crowdsecurity/crowdsec:v1.7.3
    container_name: crowdsec
    restart: unless-stopped
    environment:
      PGID: "1000"
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/postfix crowdsecurity/dovecot"
    ports:
      - "127.0.0.1:8080:8080"
    healthcheck:
      test: ["CMD", "cscli", "version"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ./volumes/crowdsec/config:/etc/crowdsec
      - ./volumes/crowdsec/data:/var/lib/crowdsec/data
      - ./config/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - ./volumes/traefik/logs:/var/log/traefik:ro
      - ./volumes/mailserver/logs:/var/log/mail:ro
      - /var/log/auth.log:/var/log/auth.log:ro
    networks:
      - web

  rapidmaker:
    build: ./apps/RapidMaker
    image: rapidmaker:latest
    container_name: rapidmaker
    restart: unless-stopped
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.rapidmaker.loadbalancer.server.port=8080"

      # HTTP -> HTTPS redirect
      - "traefik.http.routers.rapidmaker.rule=Host(`rapidmaker.pl`) || Host(`www.rapidmaker.pl`)"
      - "traefik.http.routers.rapidmaker.entrypoints=web"
      - "traefik.http.routers.rapidmaker.middlewares=redirect-to-https"

      # HTTPS
      - "traefik.http.routers.rapidmaker-secure.rule=Host(`rapidmaker.pl`) || Host(`www.rapidmaker.pl`)"
      - "traefik.http.routers.rapidmaker-secure.entrypoints=websecure"
      - "traefik.http.routers.rapidmaker-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.rapidmaker-secure.middlewares=limit-buffer-rapidmaker,ratelimit-rapidmaker"

      # Middlewares
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

      # Security Headers (global middleware)
      - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.security-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
      - "traefik.http.middlewares.security-headers.headers.permissionsPolicy=geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"
      - "traefik.http.middlewares.limit-buffer-rapidmaker.buffering.maxRequestBodyBytes=104857600"
      - "traefik.http.middlewares.limit-buffer-rapidmaker.buffering.memRequestBodyBytes=10485760"
      - "traefik.http.middlewares.ratelimit-rapidmaker.ratelimit.average=60"
      - "traefik.http.middlewares.ratelimit-rapidmaker.ratelimit.burst=120"
      - "traefik.http.middlewares.ratelimit-rapidmaker.ratelimit.period=1m"

      # CrowdSec - DISABLED FOR TESTING
      # - "traefik.http.middlewares.crowdsec-rapidmaker.plugin.crowdsec-bouncer.enabled=true"
      # - "traefik.http.middlewares.crowdsec-rapidmaker.plugin.crowdsec-bouncer.crowdseclapikey=${CROWDSEC_API_KEY}"
    networks:
      - web

  orca-worker:
    build: ./apps/RapidMaker/docker/orca-worker
    image: orca-worker:latest
    container_name: orca-worker
    restart: unless-stopped
    expose:
      - 9090
    environment:
      - ORCA_WORKER_PORT=9090
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    volumes:
      - /tmp/orca-workspace:/workspace
    networks:
      - web

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:15.1.0
    container_name: mailserver
    hostname: mail.rapidmaker.pl
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ss -lntp | grep -E ':25|:587|:993'"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 45s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "11334:11334"
    volumes:
      - ./volumes/traefik/letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
      - ./volumes/mailserver/config:/tmp/docker-mailserver
      - ./volumes/mailserver/data:/var/mail
      - ./volumes/mailserver/state:/var/mail-state
      - ./volumes/mailserver/logs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
    environment:
      # DISABLED: CrowdSec with firewall bouncer provides better protection
      # - Global threat intelligence (22k+ IPs from CAPI)
      # - Blocks for ALL services (not just mail)
      # - Faster detection with Go vs Python
      - ENABLE_FAIL2BAN=0
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mail.rapidmaker.pl
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_OAUTH2=0
      # Rspamd replaces ALL legacy anti-spam services
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_POSTGREY=0
    cap_add:
      - NET_ADMIN
    labels:
      # Traefik labels to generate SSL certificate with SANs for both mail domains
      - "traefik.enable=true"
      # HTTPS router for Rspamd web UI (port 11334) - generates cert with SANs
      - "traefik.http.routers.rspamd.rule=Host(`mail.rapidmaker.pl`) || Host(`mail.sieciowiec.xyz`)"
      - "traefik.http.routers.rspamd.entrypoints=websecure"
      - "traefik.http.routers.rspamd.tls.certresolver=letsencrypt"
      - "traefik.http.routers.rspamd.tls.domains[0].main=mail.rapidmaker.pl"
      - "traefik.http.routers.rspamd.tls.domains[0].sans=mail.sieciowiec.xyz"
      - "traefik.http.routers.rspamd.service=rspamd"
      - "traefik.http.services.rspamd.loadbalancer.server.port=11334"
    networks:
      - web

  obsidian-livesync:
    image: couchdb:3.5.0
    container_name: obsidian-livesync
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./volumes/couchdb/data:/opt/couchdb/data
      - ./volumes/couchdb/config:/opt/couchdb/etc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.obsidian-livesync.rule=Host(`obsidian-livesync.sieciowiec.xyz`)"
      - "traefik.http.routers.obsidian-livesync.entrypoints=web"
      - "traefik.http.routers.obsidian-livesync.middlewares=redirect-to-https"
      - "traefik.http.routers.obsidian-livesync-secure.rule=Host(`obsidian-livesync.sieciowiec.xyz`)"
      - "traefik.http.routers.obsidian-livesync-secure.entrypoints=websecure"
      - "traefik.http.routers.obsidian-livesync-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.obsidian-livesync-secure.service=obsidian-livesync"
      - "traefik.http.services.obsidian-livesync.loadbalancer.server.port=5984"
      - "traefik.http.routers.obsidian-livesync-secure.tls=true"
      - "traefik.http.routers.obsidian-livesync-secure.middlewares=obsidiancors,ratelimit-obsidian"

      # CORS for Obsidian
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowmethods=GET,PUT,POST,HEAD,DELETE"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolallowheaders=accept,authorization,content-type,origin,referer"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolalloworiginlist=app://obsidian.md,capacitor://localhost,http://localhost"
      - "traefik.http.middlewares.obsidiancors.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.obsidiancors.headers.addvaryheader=true"
      - "traefik.http.middlewares.obsidiancors.headers.accessControlAllowCredentials=true"

      # Rate Limiting (permissive - 300 req/min, burst 600)
      - "traefik.http.middlewares.ratelimit-obsidian.ratelimit.average=300"
      - "traefik.http.middlewares.ratelimit-obsidian.ratelimit.burst=600"
      - "traefik.http.middlewares.ratelimit-obsidian.ratelimit.period=1m"

      # CrowdSec - DISABLED FOR TESTING
      # - "traefik.http.middlewares.crowdsec-obsidian.plugin.crowdsec-bouncer.enabled=true"
      # - "traefik.http.middlewares.crowdsec-obsidian.plugin.crowdsec-bouncer.crowdseclapikey=${CROWDSEC_API_KEY}"
    networks:
      - web

  blog:
    image: ghcr.io/static-web-server/static-web-server:2.39.0
    container_name: blog
    restart: unless-stopped
    volumes:
      - ./apps/blog/public:/public:ro
    command: ["--root", "/public", "--port", "80"]
    labels:
      - "traefik.enable=true"

      # HTTP -> HTTPS redirect
      - "traefik.http.routers.blog.rule=Host(`sieciowiec.xyz`) || Host(`www.sieciowiec.xyz`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.routers.blog.middlewares=redirect-to-https"

      # HTTPS
      - "traefik.http.routers.blog-secure.rule=Host(`sieciowiec.xyz`) || Host(`www.sieciowiec.xyz`)"
      - "traefik.http.routers.blog-secure.entrypoints=websecure"
      - "traefik.http.routers.blog-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.blog.loadbalancer.server.port=80"
    networks:
      - web

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    expose:
      - 80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_DB_HOST=/var/roundcube/db
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_HOST=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_SESSION_LIFETIME=60
      - ROUNDCUBEMAIL_FORCE_HTTPS=true
    volumes:
      - ./volumes/roundcube/data:/var/roundcube/db:rw
      - ./config/roundcube/ssl-conn.php:/var/www/html/config/ssl-conn.php:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webmail.rule=Host(`webmail.rapidmaker.pl`) || Host(`webmail.sieciowiec.xyz`)"
      - "traefik.http.routers.webmail.entrypoints=web"
      - "traefik.http.routers.webmail.middlewares=redirect-to-https"
      - "traefik.http.routers.webmail-secure.rule=Host(`webmail.rapidmaker.pl`) || Host(`webmail.sieciowiec.xyz`)"
      - "traefik.http.routers.webmail-secure.entrypoints=websecure"
      - "traefik.http.routers.webmail-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.webmail-secure.tls.domains[0].main=webmail.rapidmaker.pl"
      - "traefik.http.routers.webmail-secure.tls.domains[0].sans=webmail.sieciowiec.xyz"
      - "traefik.http.services.webmail.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    name: web
    driver: bridge
